version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      WEATHER_API_URL: ${WEATHER_API_URL}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    # ports:
    #   - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d/:ro

volumes:
  postgres_data:
