global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'Grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'NginxExporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
